import type { Metadata } from "next";

import "./globals.css";
import "@/css/containers.css";
import "@/css/input.css";
import "@/css/lists.css";
import "@/css/tailwindcolors.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="corporate" lang="en">
      <body className="flex justify-center">
          {children}
      </body>
    </html>
  );
}
